### ISSUE TITLE
extension MTLRegion has wrong (+1) maxX maxY maxZ

### ISSUE THREAD

**Issue by atrbx5** [s1ddok/Alloy#123]
if my texture has size of 5
then my minX is 0
and my maxX is 4
with current implementation it's 5
~~~
public extension MTLRegion {
    var maxX: Int {
        return self.origin.x + self.size.width
    }    
    var maxY: Int {
        return self.origin.y + self.size.height
    }    
    var maxZ: Int {
        return self.origin.z + self.size.depth
    }
~~~

**Comment by s1ddok** [comment]
hmmm, yes, this seems wrong. I will try to address this asap

**Comment by s1ddok** [comment]
took me a while but I finally fixed it lol

**Comment by atrbx5** [comment]
> took me a while but I finally fixed it lol

oh yeah... Feb 2022 I was a bit distracted from making PR ;) sorry
