### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by sjmueller** [s1ddok/Alloy#68]
Please consider implementing support for Swift PM, now that it is built right into Xcode 11. Thanks!

**Comment by s1ddok** [comment]
We do have that in our plans, but Swift PM currently doesn't support Metal shaders in frameworks, so some of functionality will not be available.

**Comment by sjmueller** [comment]
Looks like Swift PM will support metal shaders in the near future, as [proposed here](https://forums.swift.org/t/draft-proposal-package-resources/29941). Fingers crossed!

In the mean time perhaps Carthage support could be added? Our projects don't use CocoaPods, so Carthage would be super helpful until Swift PM lands.

**Comment by s1ddok** [comment]
Yup, just being waiting for that one! 

I can't promise that myself since we don't use Carthage, but I will be happy to accept contribution. Alloy builds are fairly simple so that shouldn't be a problem

**Comment by s1ddok** [comment]
@sjmueller good news! #95 introduces a full-fledged SwiftPM support with all shaders and kernels. We will merge it once a stable Xcode 12 version lands.

**Comment by sjmueller** [comment]
great news! looking fwd to trying the latest updates

**Comment by s1ddok** [comment]
so happy to finally close this!

**Comment by sjmueller** [comment]
happy too! a long time coming 🎉
